package model

import (
	"fmt"
)

const (
	NOT_BLANK_ERR_TYPE   = "NOT_BLANK"
	MUST_NUMBER_ERR_TYPE = "MUST_NUMBER"
	MUST_STRING_ERR_TYPE = "MUST_STRING"
	NOT_VALID_ERR_TYPE   = "NOT_VALID"
	//NOT_MATCH_ERR_TYPE              = "NOT_MATCH"

	NOT_FOUND_ERR_TYPE              = "NOT_FOUND"
	USERNAME_OR_PASSWORD_INVALID    = "USERNAME_OR_PASSWORD_INVALID"
	PASSWORD_INVALID                = "PASSWORD_INVALID"
	OLD_PASSWORD_CANNOT_BE_MATCH    = "OLD_PASSWORD_CANNOT_BE_MATCH"
	CONFIRM_PASSWORD_NOT_MATCH      = "CONFIRM_PASSWORD_NOT_MATCH"
	AUTHENTICATION_FAILURE_ERR_TYPE = "AUTHENTICATION_FAILURE"
	AGENT_BLOCKED                   = "AGENT_BLOCKED"
	AGENT_INACTIVE                  = "AGENT_INACTIVE"
	AGENT_NOT_FOUND                 = "AGENT_NOT_FOUND"
	INTERNAL_ERROR_ERR_TYPE         = "INTERNAL_ERROR"
	STOCK_EXCEEDES_LIMIT            = "STOCK_EXCEEDES_LIMIT"
	PRODUCT_NOT_FOUND               = "PRODUCT_NOT_FOUND"
	ORDER_NOT_FOUND                 = "ORDER_NOT_FOUND"
	SALES_NOT_FOUND                 = "SALES_NOT_FOUND"
	CART_NOT_FOUND                  = "CART_NOT_FOUND"
	EXTENSION_NOT_ALLOWED           = "EXTENSION_NOT_ALLOWED"
	UNAUTHORIZED                    = "UNAUTHORIZED"

	CANNOT_BE_NEGATIVE_NUMBER = "CANNOT_BE_NEGATIVE_NUMBER"
)

func Min(x interface{}) string {
	return fmt.Sprintf("MIN_%v", x)
}

func Max(x interface{}) string {
	return fmt.Sprintf("MAX_%v", x)
}
